version: "3"
services:
  mysql:
    container_name: wants_database
    image: library/mysql:5.7
    volumes:
      - mysql_volumes:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

  application:
      container_name: wants_application
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./:/home
      links:
        - mysql
      ports:
        - "5050:5050"
      environment:
        - DB_HOST=${DB_HOST}
        - DB_USER=${MYSQL_USER}
        - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - DB_DATABASE=${MYSQL_DATABASE}

volumes:
  mysql_volumes:
    driver: local
