version: "3"
services:
  mysql:
    container_name: wants_database
    image: library/mysql:5.7
    restart: always
    volumes:
      - mysql_volumes:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  application:
    container_name: wants_application
    restart: always
    build:
      context: .
      dockerfile: Dockerfiles/application.Dockerfile
    volumes:
      - ./:/home
    links:
      - mysql
      - nginx
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
    command : sh -c "sleep 15 | python3 application.py"

  swagger:
    container_name: wants_swagger
    restart: always
    build:
      context: .
      dockerfile: Dockerfiles/swagger.Dockerfile
    ports:
      - "3000:3000"
    links:
      - nginx
    command: sh -c "node index.js"

  nginx:
    container_name: wants_nginx
    restart: always
    build:
      context: .
      dockerfile: Dockerfiles/nginx.Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

volumes:
  mysql_volumes:
    driver: local
